In [126]:
import pandas as pd
import geopandas
# cross_lochs = pd.read_csv('../cross_lochs_6_classes_for_ML.csv')
cross_lochs = pd.read_csv('../transformed_spectral_signatures/first_derivative_98_sample.csv')
# cross_lochs = pd.read_csv('../transformed_spectral_signatures/BDNA_98_sample.csv')

cross_lochs['geometry'] = geopandas.GeoSeries.from_wkt(cross_lochs['geometry'])

cross_lochs_gdf = geopandas.GeoDataFrame(cross_lochs, geometry='geometry')

cross_lochs_gdf.head()


Unnamed: 0     band1     band2     band3     band4     band5     band6  \
0         412  0.003409  0.003283  0.004620  0.006938  0.007003  0.009061   
1         413  0.002237  0.005423  0.006024  0.006861  0.007332  0.010247   
2         617  0.000951  0.005150  0.005988  0.006720  0.007361  0.010606   
3         821  0.002823  0.002804  0.005312  0.006705  0.007482  0.009891   
4         822  0.002991  0.004075  0.004819  0.005989  0.007388  0.009729   

      band7     band8     band9  ...   band353   band354   band355   band356  \
0  0.011035  0.013070  0.016138  ...  0.090197  0.088069  0.092271  0.089105   
1  0.012456  0.013884  0.017221  ...  0.096534  0.098906  0.093759  0.099614   
2  0.012082  0.014234  0.015797  ...  0.096551  0.097626  0.096350  0.095506   
3  0.012163  0.013613  0.016889  ...  0.097774  0.096034  0.095319  0.100638   
4  0.012035  0.013280  0.016029  ...  0.089470  0.091884  0.090096  0.090060   

    band357   band358  POINTID                        geometry  GRID_CODE  \
0  0.089418  0.091109      413  POINT (444754.308 6472595.655)   0.003409   
1  0.096711  0.096978      414  POINT (444759.308 6472595.655)   0.002237   
2  0.098056  0.096859      618  POINT (444764.308 6472590.655)   0.000951   
3  0.097645  0.098486      822  POINT (444769.308 6472585.655)   0.002823   
4  0.089917  0.090350      823  POINT (444774.308 6472585.655)   0.002991   

           PFT  
0  calluna_mix  
1  calluna_mix  
2  calluna_mix  
3  calluna_mix  
4  calluna_mix  

[5 rows x 363 columns]

In [127]:
from sklearn.model_selection import train_test_split


train_shrub_sphagnum, test_shrub_sphagnum = train_test_split(cross_lochs_gdf[cross_lochs_gdf['PFT'].str.contains('shrub_sphagnum')], test_size=0.2)
train_water, test_water = train_test_split(cross_lochs_gdf[cross_lochs_gdf['PFT'].str.contains('water')], test_size=0.2)
train_sphagnum_r, test_sphagnum_r = train_test_split(cross_lochs_gdf[cross_lochs_gdf['PFT'].str.contains('spahgnum_r')], test_size=0.2)
train_pool_bogbean, test_pool_bogbean = train_test_split(cross_lochs_gdf[cross_lochs_gdf['PFT'].str.contains('pool_bogbean')], test_size=0.2)
train_calluna_mix, test_calluna_mix = train_test_split(cross_lochs_gdf[cross_lochs_gdf['PFT'].str.contains('calluna_mix')], test_size=0.2)
train_rushes_sedges, test_rushes_sedges = train_test_split(cross_lochs_gdf[cross_lochs_gdf['PFT'].str.contains('rushes_sedges')], test_size=0.2)


train_frames = [train_shrub_sphagnum, train_water, train_sphagnum_r, train_pool_bogbean, train_calluna_mix, train_rushes_sedges]
test_frames = [test_shrub_sphagnum, test_water, test_sphagnum_r, test_pool_bogbean, test_calluna_mix, test_rushes_sedges]


train = pd.concat(train_frames)
test = pd.concat(test_frames)


train.head()

Unnamed: 0     band1     band2     band3     band4     band5     band6  \
365       32796  0.000877  0.001964  0.004111  0.005402  0.006280  0.009506   
367       33197  0.000785  0.001853  0.004034  0.005049  0.006423  0.008827   
389       39878  0.000182  0.001286  0.003257  0.004290  0.004870  0.006696   
348       25706  0.000953  0.002424  0.004626  0.006270  0.008241  0.011412   
358       31373  0.000847  0.001996  0.004097  0.005045  0.006335  0.008624   

        band7     band8     band9  ...   band353   band354   band355  \
365  0.011431  0.013257  0.015780  ...  0.088172  0.090491  0.088050   
367  0.010738  0.012786  0.015068  ...  0.089420  0.089341  0.092726   
389  0.008339  0.009924  0.011579  ...  0.052553  0.051638  0.054732   
348  0.013214  0.015599  0.017165  ...  0.095653  0.097658  0.091707   
358  0.011031  0.012736  0.015134  ...  0.092468  0.091503  0.093610   

      band356   band357   band358  POINTID                        geometry  \
365  0.088148  0.088512  0.089962    32797  POINT (445289.308 6471800.655)   
367  0.087907  0.089701  0.090068    33198  POINT (445264.308 6471790.655)   
389  0.053883  0.051251  0.049151    39879  POINT (445174.308 6471625.655)   
348  0.097261  0.092991  0.093669    25707  POINT (445364.308 6471975.655)   
358  0.092184  0.092059  0.090405    31374  POINT (445279.308 6471835.655)   

     GRID_CODE             PFT  
365   0.000877  shrub_sphagnum  
367   0.000785  shrub_sphagnum  
389   0.000182  shrub_sphagnum  
348   0.000953  shrub_sphagnum  
358   0.000847  shrub_sphagnum  

[5 rows x 363 columns]

In [128]:
# initial dataset

# x_train = train[train.columns[1:359]]
# y_train = train[train.columns[362]]

# x_test = test[test.columns[1:359]]
# y_test = test[test.columns[362]]

# x_test.head(2)


#derivatives dataset

x_train = train[train.columns[1:359]]
y_train = train[train.columns[359]]

x_test = test[test.columns[1:359]]
y_test = test[test.columns[359]]

x_test.head(2)

band1     band2     band3     band4     band5     band6     band7  \
305  0.001321  0.002202  0.003517  0.004093  0.005342  0.006997  0.008817   
328  0.000968  0.002156  0.003102  0.004872  0.005900  0.007770  0.008936   

        band8     band9    band10  ...   band349   band350  band351   band352  \
305  0.010151  0.012477  0.014779  ...  0.059359  0.060163  0.05791  0.056546   
328  0.010186  0.012712  0.014744  ...  0.055692  0.055042  0.05631  0.055304   

      band353   band354   band355   band356   band357   band358  
305  0.059442  0.057537  0.056969  0.057905  0.059816  0.055720  
328  0.055399  0.057340  0.056296  0.055808  0.055411  0.057162  

[2 rows x 358 columns]

In [129]:
from sklearn import dummy

dc = dummy.DummyClassifier()
dc.fit(x_train, y_train)
dc_score = dc.score(x_test, y_test)

print("Baseline Accuracy:", dc_score)


Baseline Accuracy: 0.16666666666666666


In [130]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt

svc = SVC(kernel='linear')
svc.fit(x_train, y_train)
print(svc.score(x_train, y_train))

y_pred = svc.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

scores = cross_val_score(svc, x_train, y_train, cv=3)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.688034188034188
[[18  0  0  2  0  0]
 [ 0 13  0  4  0  3]
 [ 1  0  7  0  9  3]
 [ 2  9  0  9  0  0]
 [ 2  0  4  0 14  0]
 [ 5  0  0  0  0 15]]
                precision    recall  f1-score   support

   calluna_mix       0.64      0.90      0.75        20
  pool_bogbean       0.59      0.65      0.62        20
 rushes_sedges       0.64      0.35      0.45        20
shrub_sphagnum       0.60      0.45      0.51        20
    spahgnum_r       0.61      0.70      0.65        20
         water       0.71      0.75      0.73        20

      accuracy                           0.63       120
     macro avg       0.63      0.63      0.62       120
  weighted avg       0.63      0.63      0.62       120

0.66 accuracy with a standard deviation of 0.04


In [131]:
scores = cross_val_score(svc, x_test, y_test, cv=3)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.60 accuracy with a standard deviation of 0.05


In [132]:
# now want to predict for the whole dataset using the svc
cross_lochs = pd.read_csv('../cross_lochs_gdf.csv')

cross_lochs['geometry'] = geopandas.GeoSeries.from_wkt(cross_lochs['geometry'])

cross_lochs_full_gdf = geopandas.GeoDataFrame(cross_lochs, geometry='geometry')


In [133]:
x = cross_lochs_full_gdf[cross_lochs_gdf.columns[1:359]]
svc_pred_full = svc.predict(x)

In [134]:
# initial dataset

# model_results_full = cross_lochs_full_gdf[cross_lochs_full_gdf.columns[360:362]]

# derivatives

model_results_full = cross_lochs_full_gdf[cross_lochs_full_gdf.columns[359:361]]

model_results_full = model_results_full.assign(svc_pred_full = svc_pred_full)

model_results_full.head()

geometry  GRID_CODE svc_pred_full
0  POINT (444724.308 6472605.655)   0.001099    spahgnum_r
1  POINT (444729.308 6472605.655)   0.003365    spahgnum_r
2  POINT (444734.308 6472605.655)   0.002603   calluna_mix
3  POINT (444739.308 6472605.655)   0.002381   calluna_mix
4  POINT (444744.308 6472605.655)   0.002342   calluna_mix

In [135]:
model_results_full.to_file("cross_lochs_svc_98_sample_full_first_derivative_0.2_gdf.shp")

model_results_full.to_csv("cross_lochs_svc_98_sample_full_first_derivative_0.2_gdf.csv")

/tmp/ipykernel_7600/785695082.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  model_results_full.to_file("cross_lochs_svc_98_sample_full_0.2_gdf.shp")


In [136]:
# splitting into bands

cross_lochs_vis_bands = cross_lochs_gdf.iloc[:,6:66]
cross_lochs_RE_bands = cross_lochs_gdf.iloc[:,62:76]
cross_lochs_NIR_bands = cross_lochs_gdf.iloc[:,66:186]
cross_lochs_SWIR_bands = cross_lochs_gdf.iloc[:,186:359]

cross_lochs_general = cross_lochs_gdf.iloc[:,359:363]

cross_lochs_vis = pd.concat([cross_lochs_vis_bands, cross_lochs_general], axis=1)
cross_lochs_RE = pd.concat([cross_lochs_RE_bands, cross_lochs_general], axis=1)
cross_lochs_NIR = pd.concat([cross_lochs_NIR_bands, cross_lochs_general], axis = 1)
cross_lochs_SWIR = pd.concat([cross_lochs_SWIR_bands, cross_lochs_general], axis = 1)


cross_lochs_RE.head()

band62    band63    band64    band65    band66    band67    band68  \
0  0.074329  0.082080  0.093771  0.108923  0.122308  0.137470  0.152759   
1  0.080827  0.088822  0.098916  0.112827  0.125882  0.139206  0.150463   
2  0.078536  0.085416  0.095944  0.107573  0.120429  0.133712  0.146125   
3  0.081194  0.088930  0.099797  0.111447  0.123777  0.135808  0.148243   
4  0.076062  0.082774  0.092966  0.105358  0.118332  0.130206  0.141944   

     band69    band70    band71    band72    band73    band74    band75  \
0  0.167381  0.181403  0.192789  0.203651  0.212076  0.220560  0.224350   
1  0.163993  0.174413  0.183864  0.193155  0.199498  0.205185  0.211138   
2  0.157834  0.169158  0.179111  0.188062  0.195035  0.200163  0.205071   
3  0.158045  0.167228  0.176402  0.185572  0.191944  0.197850  0.200583   
4  0.153875  0.163983  0.172715  0.181595  0.188657  0.193181  0.198372   

   POINTID                        geometry  GRID_CODE          PFT  
0      413  POINT (444754.308 6472595.655)   0.003409  calluna_mix  
1      414  POINT (444759.308 6472595.655)   0.002237  calluna_mix  
2      618  POINT (444764.308 6472590.655)   0.000951  calluna_mix  
3      822  POINT (444769.308 6472585.655)   0.002823  calluna_mix  
4      823  POINT (444774.308 6472585.655)   0.002991  calluna_mix

In [137]:
# VIS

train_shrub_sphagnum, test_shrub_sphagnum = train_test_split(cross_lochs_vis[cross_lochs_vis['PFT'].str.contains('shrub_sphagnum')], test_size=0.2)
train_water, test_water = train_test_split(cross_lochs_vis[cross_lochs_vis['PFT'].str.contains('water')], test_size=0.2)
train_sphagnum_r, test_sphagnum_r = train_test_split(cross_lochs_vis[cross_lochs_vis['PFT'].str.contains('spahgnum_r')], test_size=0.2)
train_pool_bogbean, test_pool_bogbean = train_test_split(cross_lochs_vis[cross_lochs_vis['PFT'].str.contains('pool_bogbean')], test_size=0.2)
train_calluna_mix, test_calluna_mix = train_test_split(cross_lochs_vis[cross_lochs_vis['PFT'].str.contains('calluna_mix')], test_size=0.2)
train_rushes_sedges, test_rushes_sedges = train_test_split(cross_lochs_vis[cross_lochs_vis['PFT'].str.contains('rushes_sedges')], test_size=0.2)

train_frames = [train_shrub_sphagnum, train_water, train_sphagnum_r, train_pool_bogbean, train_calluna_mix, train_rushes_sedges]
test_frames = [test_shrub_sphagnum, test_water, test_sphagnum_r, test_pool_bogbean, test_calluna_mix, test_rushes_sedges]


train = pd.concat(train_frames)
test = pd.concat(test_frames)

# initial

# x_train = train[train.columns[0:60]]
# y_train = train[train.columns[63]]

# x_test = test[test.columns[0:60]]
# y_test = test[test.columns[63]]

# derivative

x_train = train[train.columns[0:60]]
y_train = train[train.columns[60]]

x_test = test[test.columns[0:60]]
y_test = test[test.columns[60]]


svc = SVC(kernel='linear')
svc.fit(x_train, y_train)
print(svc.score(x_train, y_train))

y_pred = svc.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

scores = cross_val_score(svc, x_train, y_train, cv=3)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

scores_test = cross_val_score(svc, x_test, y_test, cv=3)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores_test.mean(), scores_test.std()))


0.43803418803418803
[[20  0  0  0  0  0]
 [14  0  3  0  0  3]
 [ 4  0  0  0 15  1]
 [16  0  4  0  0  0]
 [ 3  0  2  0 14  1]
 [ 4  0  0  0  0 16]]
                precision    recall  f1-score   support

   calluna_mix       0.33      1.00      0.49        20
  pool_bogbean       0.00      0.00      0.00        20
 rushes_sedges       0.00      0.00      0.00        20
shrub_sphagnum       0.00      0.00      0.00        20
    spahgnum_r       0.48      0.70      0.57        20
         water       0.76      0.80      0.78        20

      accuracy                           0.42       120
     macro avg       0.26      0.42      0.31       120
  weighted avg       0.26      0.42      0.31       120

0.43 accuracy with a standard deviation of 0.00
0.18 accuracy with a standard deviation of 0.08


/home/rzw/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/rzw/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/rzw/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [138]:
# now want to predict for the whole dataset using the svc

x = cross_lochs_full_gdf[cross_lochs_gdf.columns[6:66]]

svc_pred_full = svc.predict(x)


# initial
# model_results_full = cross_lochs_full_gdf[cross_lochs_full_gdf.columns[360:362]]

# derivative
model_results_full = cross_lochs_gdf[cross_lochs_gdf.columns[359:361]]

model_results_full = model_results_full.assign(svc_pred_full = svc_pred_full)



model_results_full.to_file("cross_lochs_SVC_98_sample_full_vis_first_derivative_0.2_gdf.shp")

model_results_full.to_csv("cross_lochs_SVC_98_sample_full_vis_first_derivative_0.2_gdf.csv")


/tmp/ipykernel_7600/962570259.py:18: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  model_results_full.to_file("cross_lochs_SVC_98_sample_full_vis_0.2_gdf.shp")


In [139]:
# RE

train_shrub_sphagnum, test_shrub_sphagnum = train_test_split(cross_lochs_RE[cross_lochs_RE['PFT'].str.contains('shrub_sphagnum')], test_size=0.2)
train_water, test_water = train_test_split(cross_lochs_RE[cross_lochs_RE['PFT'].str.contains('water')], test_size=0.2)
train_sphagnum_r, test_sphagnum_r = train_test_split(cross_lochs_RE[cross_lochs_RE['PFT'].str.contains('spahgnum_r')], test_size=0.2)
train_pool_bogbean, test_pool_bogbean = train_test_split(cross_lochs_RE[cross_lochs_RE['PFT'].str.contains('pool_bogbean')], test_size=0.2)
train_calluna_mix, test_calluna_mix = train_test_split(cross_lochs_RE[cross_lochs_RE['PFT'].str.contains('calluna_mix')], test_size=0.2)
train_rushes_sedges, test_rushes_sedges = train_test_split(cross_lochs_RE[cross_lochs_RE['PFT'].str.contains('rushes_sedges')], test_size=0.2)

train_frames = [train_shrub_sphagnum, train_water, train_sphagnum_r, train_pool_bogbean, train_calluna_mix, train_rushes_sedges]
test_frames = [test_shrub_sphagnum, test_water, test_sphagnum_r, test_pool_bogbean, test_calluna_mix, test_rushes_sedges]


train = pd.concat(train_frames)
test = pd.concat(test_frames)


# intial
# x_train = train[train.columns[0:14]]
# y_train = train[train.columns[17]]

# x_test = test[test.columns[0:14]]
# y_test = test[test.columns[17]]

# derivatives
x_train = train[train.columns[0:14]]
y_train = train[train.columns[14]]

x_test = test[test.columns[0:14]]
y_test = test[test.columns[14]]


svc = SVC(kernel='linear')
svc.fit(x_train, y_train)
print(svc.score(x_train, y_train))

y_pred = svc.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

scores = cross_val_score(svc, x_train, y_train, cv=3)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

scores_test = cross_val_score(svc, x_test, y_test, cv=3)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores_test.mean(), scores_test.std()))


0.5106837606837606
[[20  0  0  0  0  0]
 [ 3  7  0  2  0  8]
 [ 4  1  0  1 12  2]
 [14  4  0  1  0  1]
 [ 0  0  0  0 20  0]
 [ 2  0  0  0  0 18]]
                precision    recall  f1-score   support

   calluna_mix       0.47      1.00      0.63        20
  pool_bogbean       0.58      0.35      0.44        20
 rushes_sedges       0.00      0.00      0.00        20
shrub_sphagnum       0.25      0.05      0.08        20
    spahgnum_r       0.62      1.00      0.77        20
         water       0.62      0.90      0.73        20

      accuracy                           0.55       120
     macro avg       0.42      0.55      0.44       120
  weighted avg       0.42      0.55      0.44       120

0.50 accuracy with a standard deviation of 0.02
0.47 accuracy with a standard deviation of 0.10


/home/rzw/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/rzw/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/rzw/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [140]:
# now want to predict for the whole dataset using the svc

x = cross_lochs_full_gdf[cross_lochs_gdf.columns[62:76]]

svc_pred_full = svc.predict(x)



# initial
# model_results_full = cross_lochs_full_gdf[cross_lochs_full_gdf.columns[360:362]]

# derivative
model_results_full = cross_lochs_gdf[cross_lochs_gdf.columns[359:361]]

model_results_full = model_results_full.assign(svc_pred_full = svc_pred_full)



model_results_full.to_file("cross_lochs_SVC_98_sample_full_re_first_derivative_0.2_gdf.shp")

model_results_full.to_csv("cross_lochs_SVC_98_sample_full_re_first_derivative_0.2_gdf.csv")

/tmp/ipykernel_7600/2926595207.py:19: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  model_results_full.to_file("cross_lochs_SVC_98_sample_full_re_0.2_gdf.shp")


In [141]:
# NIR

train_shrub_sphagnum, test_shrub_sphagnum = train_test_split(cross_lochs_NIR[cross_lochs_NIR['PFT'].str.contains('shrub_sphagnum')], test_size=0.2)
train_water, test_water = train_test_split(cross_lochs_NIR[cross_lochs_NIR['PFT'].str.contains('water')], test_size=0.2)
train_sphagnum_r, test_sphagnum_r = train_test_split(cross_lochs_NIR[cross_lochs_NIR['PFT'].str.contains('spahgnum_r')], test_size=0.2)
train_pool_bogbean, test_pool_bogbean = train_test_split(cross_lochs_NIR[cross_lochs_NIR['PFT'].str.contains('pool_bogbean')], test_size=0.2)
train_calluna_mix, test_calluna_mix = train_test_split(cross_lochs_NIR[cross_lochs_NIR['PFT'].str.contains('calluna_mix')], test_size=0.2)
train_rushes_sedges, test_rushes_sedges = train_test_split(cross_lochs_NIR[cross_lochs_NIR['PFT'].str.contains('rushes_sedges')], test_size=0.2)

train_frames = [train_shrub_sphagnum, train_water, train_sphagnum_r, train_pool_bogbean, train_calluna_mix, train_rushes_sedges]
test_frames = [test_shrub_sphagnum, test_water, test_sphagnum_r, test_pool_bogbean, test_calluna_mix, test_rushes_sedges]


train = pd.concat(train_frames)
test = pd.concat(test_frames)

# initial
# x_train = train[train.columns[0:120]]
# y_train = train[train.columns[123]]

# x_test = test[test.columns[0:120]]
# y_test = test[test.columns[123]]

# derivatives
x_train = train[train.columns[0:120]]
y_train = train[train.columns[120]]

x_test = test[test.columns[0:120]]
y_test = test[test.columns[120]]


svc = SVC(kernel='linear')
svc.fit(x_train, y_train)
print(svc.score(x_train, y_train))

y_pred = svc.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

scores = cross_val_score(svc, x_train, y_train, cv=3)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

scores_test = cross_val_score(svc, x_test, y_test, cv=3)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores_test.mean(), scores_test.std()))


0.6153846153846154
[[17  0  0  3  0  0]
 [ 0 13  0  6  0  1]
 [ 0  1  6  0 12  1]
 [ 4  2  0 13  0  1]
 [ 0  0  1  0 19  0]
 [ 5  0  0  1  0 14]]
                precision    recall  f1-score   support

   calluna_mix       0.65      0.85      0.74        20
  pool_bogbean       0.81      0.65      0.72        20
 rushes_sedges       0.86      0.30      0.44        20
shrub_sphagnum       0.57      0.65      0.60        20
    spahgnum_r       0.61      0.95      0.75        20
         water       0.82      0.70      0.76        20

      accuracy                           0.68       120
     macro avg       0.72      0.68      0.67       120
  weighted avg       0.72      0.68      0.67       120

0.60 accuracy with a standard deviation of 0.03
0.60 accuracy with a standard deviation of 0.05


In [142]:
# now want to predict for the whole dataset using the svc

x = cross_lochs_gdf[cross_lochs_gdf.columns[66:186]]

svc_pred_full = svc.predict(x)



# initial
# model_results_full = cross_lochs_gdf[cross_lochs_gdf.columns[360:362]]

# derivatives
model_results_full = cross_lochs_gdf[cross_lochs_gdf.columns[359:361]]

model_results_full = model_results_full.assign(svc_pred_full = svc_pred_full)



model_results_full.to_file("cross_lochs_SVC_98_sample_full_nir_first_derivative_0.2_gdf.shp")

model_results_full.to_csv("cross_lochs_SVC_98_sample_full_nir_first_derivative_0.2_gdf.csv")

In [143]:
# SWIR

train_shrub_sphagnum, test_shrub_sphagnum = train_test_split(cross_lochs_SWIR[cross_lochs_SWIR['PFT'].str.contains('shrub_sphagnum')], test_size=0.2)
train_water, test_water = train_test_split(cross_lochs_SWIR[cross_lochs_SWIR['PFT'].str.contains('water')], test_size=0.2)
train_sphagnum_r, test_sphagnum_r = train_test_split(cross_lochs_SWIR[cross_lochs_SWIR['PFT'].str.contains('spahgnum_r')], test_size=0.2)
train_pool_bogbean, test_pool_bogbean = train_test_split(cross_lochs_SWIR[cross_lochs_SWIR['PFT'].str.contains('pool_bogbean')], test_size=0.2)
train_calluna_mix, test_calluna_mix = train_test_split(cross_lochs_SWIR[cross_lochs_SWIR['PFT'].str.contains('calluna_mix')], test_size=0.2)
train_rushes_sedges, test_rushes_sedges = train_test_split(cross_lochs_SWIR[cross_lochs_SWIR['PFT'].str.contains('rushes_sedges')], test_size=0.2)

train_frames = [train_shrub_sphagnum, train_water, train_sphagnum_r, train_pool_bogbean, train_calluna_mix, train_rushes_sedges]
test_frames = [test_shrub_sphagnum, test_water, test_sphagnum_r, test_pool_bogbean, test_calluna_mix, test_rushes_sedges]


train = pd.concat(train_frames)
test = pd.concat(test_frames)

# initial
# x_train = train[train.columns[0:173]]
# y_train = train[train.columns[176]]

# x_test = test[test.columns[0:173]]
# y_test = test[test.columns[176]]

# derivatives
x_train = train[train.columns[0:173]]
y_train = train[train.columns[173]]

x_test = test[test.columns[0:173]]
y_test = test[test.columns[173]]

svc = SVC(kernel='linear')
svc.fit(x_train, y_train)
print(svc.score(x_train, y_train))

y_pred = svc.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

scores = cross_val_score(svc, x_train, y_train, cv=3)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

scores_test = cross_val_score(svc, x_test, y_test, cv=3)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores_test.mean(), scores_test.std()))


0.6196581196581197
[[20  0  0  0  0  0]
 [ 6  3  0  8  0  3]
 [ 1  1  3  0 11  4]
 [12  1  0  6  0  1]
 [ 1  0  5  0 14  0]
 [ 3  0  0  0  0 17]]
                precision    recall  f1-score   support

   calluna_mix       0.47      1.00      0.63        20
  pool_bogbean       0.60      0.15      0.24        20
 rushes_sedges       0.38      0.15      0.21        20
shrub_sphagnum       0.43      0.30      0.35        20
    spahgnum_r       0.56      0.70      0.62        20
         water       0.68      0.85      0.76        20

      accuracy                           0.53       120
     macro avg       0.52      0.53      0.47       120
  weighted avg       0.52      0.53      0.47       120

0.59 accuracy with a standard deviation of 0.02
0.50 accuracy with a standard deviation of 0.04


In [144]:
# now want to predict for the whole dataset using the svc

x = cross_lochs_full_gdf[cross_lochs_gdf.columns[186:359]]


svc_pred_full = svc.predict(x)



# initial
# model_results_full = cross_lochs_gdf[cross_lochs_gdf.columns[360:362]]

# derivative
model_results_full = cross_lochs_gdf[cross_lochs_gdf.columns[359:361]]

model_results_full = model_results_full.assign(svc_pred_full = svc_pred_full)


model_results_full.to_file("cross_lochs_SVC_98_sample_full_swir_first_derivative_0.2_gdf.shp")

model_results_full.to_csv("cross_lochs_SVC_98_sample_full_swir_first_derivative_0.2_gdf.csv")